---
title: 提问的艺术
subtitle: 《提问的智慧》与《别想弱智一样提问》读后感
author: 王嘉宸（广东工业大学\ 计算机学院）
date: 2022-11-28
keywords: [提问, 读后感]

format:
  pdf:
    pdf-engine: xelatex
    documentclass: ctexart
    papersize: a4
    indent: true
    geometry: top=0.5cm, bottom=1.5cm, left=2cm, right=2cm
---

问问题，是学习过程中必不可少的一个环节。一个人想要完全理解清楚一个知识，没有疑问是不可能的。
提问题，看似很容易，实际上并非如此。如何有效准确地表述出自己的问题，同时能够吸引别人对问题进行解答，这是一门学问。
阅读完毕《提问的智慧》和《别想弱智一样提问》两文后，我初步明确了“好的问题”这个概念。

一个好的问题应当包含如下特性：

1. 非无脑的；
2. 清晰准确的；
3. 礼貌且易于回复的。

下面我将分别具体阐述我对以上三个特性的理解。

问出问题首先必须是非无脑的，换句话说，是经过大脑思考的。说到这里，就避不开两个词了“STFW”和“RTFM”。
何为“经过大脑思考”，我的理解是先要经过“STFW”和“RTFM”，即遇到问题，不要是将问题抛出来给别人，做“伸手党”。
作为一个大学生，或者说，未来的科研人员，要培养自己独立解决问题的能力。
当今时代，网络资源是很丰富的，对于“xxx是什么？”“xxx怎么搞？”之类的问题，90%都能经过搜索引擎得到相应的答案。
他人的时间是有限的，将这些自己稍微动动手就可以获取到的抛给他人“帮你”解决未免有点不道德。

一个有趣或者有价值的问题一定是清晰准确的。清晰指问题的主题明确，语法正确（尤其是在外文论坛提问时），标题有意义且言简意赅，能够指明疑问（或问题）所在，精简代码，提供测试样例。
对于Bug Report，最好有详尽的现象或报错和复现过程。
正确指发帖的场合分区正确，描述的现象和贴出的代码准确，准确描述问题，不“裁剪”或者想当然，不发重复问题。
明确问题和检查准确性的过程，实际上也在帮助自己理清思路，思路清晰了，检查没有缺漏了，有时问题也自然而然解决了。

在高中初学Linux，安装ArchLinux的时候，我就曾有类似体验。问题是在cryptosetup建立LUKS容器，对文件系统进行加密后新安装好的系统无法正常启动。
加载initial ramfs时所查询的分区uuid不是解密后的uuid，导致grub找不到内核镜像。
虽然当时不知道“STFW”的概念，但是自然，安装ArchLinux肯定要参考ArchWiki，参考别人的Blog，所以就去找相关材料了。
仔细检查了一遍流程，发现“貌似”没什么问题，就准备去发帖询问。发前看到版规里提到“善用站内搜索”，于是简单站内查找了一番，发现了相似的情况。
参考他人经历后发现是因为grub修改default.conf中的部分配置后需要重新安装，后问题解决。

在查询过程中，那时的我实际上就已经认识到好的问题的重要性。我查询的流程实际上就是“如何聪明地提问”的过程，而搜索到的他人的问题描述清晰准确。
正因如此，我才能快速发现类似情况，排查出错误进行修正。

一个好的提问还应该是文明且礼貌的。社区中没有人义务回答他人的问题，大家的时间都很宝贵，因此想请求别人的帮助，首先态度要端正。
提问中多用“请”，多道谢，不要要求别人回复到指定的邮箱，从而造成困扰。问题解决后予以简短说明，受到了社区帮助，自然也应当回馈社区，说明问题如何解决的也是为社区知识库做出了贡献。

这就是我阅读材料后得出的对“好的问题”的理解。好的问题吸引人回答，提出好的问题帮助提问者成长。
